// dr atef = 15
// dr hasan = 4
export const del = [
  {
    imgUrl: "/assets/dr/maledoc.png",
    name: "Dr. Muhammed Farouq",
    Nationality: "Pakistan",
    Qualification: "MBBS MSC Gastroenterology UK",
    Experience: " 15 years",
    position: "Internal Medicine and Gastroenterology Specialist",
    department: ["gastroenterology"],
    search: "Gastroenterology",
    License: ["Member of Saudi Gastroenterology Association"],
    skills: [
      "Herpetology and Endoscopy",
      "Diagnose and treating internal Medicine",
      "Liver Diseases",
      "Gastrointestinal",
      "Pancreatic Diseases",
    ],
    mobno: "+00 0000 0000 00",
    email: "roberto@medwise.com",
    linkto: "Muhammed_Farouq",
  },
  {
    name: "Dr. Ibrahim Rushdi",
    License: [
      "Membership of the Jordanian Medical Council",
      "Colon and gastrointestinal tumors",
      "Doctors Membership ",
    ],
  },
  {
    imgUrl: "/assets/dr/femaledoc.png",
    moid: "61efcf909e4660080341bddb",
    name: "Dr. Moza ",
    namear: "Dr. Moza Al Mazrouei",
    positionar: "Dermatology and cosmetic consultant",
    Nationality: "The United Arab Emirates",
    Qualification: [],
    Experience: " 20 years",
    position: "Dermatology and cosmetic consultant",
    department: ["dermatology"],
    search: "dermatology",
    searchid: ["61dc0c29b24354b161efe871"],
    skills: ["Laser", "Botox", "Fillers", "Plasma", "Cleansing "],
    skillsar: ["Laser", "Botox", "Fillers", "Plasma", "Cleansing "],
    mobno: "+00 0000 0000 00",
    email: "roberto@medwise.com",
    linkto: "dr_mosa",
  },
  {
    imgUrl: "/assets/dr/femaledoc.png",
    name: "Dr. Moza ",
    namear: "د. موزة المزروعي",
    positionar: "استشارية جلدية وتجميل",
    Nationality: "الامارات العربية المتحدة",
    Qualification: ["البورد الأردني في الجراحة العامة"],
    Experience: " 20 سنة",
    position: "Dermatology and cosmetic consultant",
    department: ["dermatology"],
    search: "dermatology",
    searchid: ["61dc0c29b24354b161efe871"],
    skills: ["Laser", "Botox", "fillers", "Plasma", "Cleansing "],
    skillsar: ["فلر", "بوتوكس", "بلازما", "تنظيف بشرة ", "ليزر"],
    mobno: "+00 0000 0000 00",
    email: "roberto@medwise.com",
    linkto: "dr_mosa",
  },
  {
    imgUrl: "/assets/dr/maledoc.png",
    moid: "61dc0fa8b24354b161f22f51",
    name: "Dr. Abeer Alotaibi",
    namear: "Dr. Abeer Alotaibi",
    positionar: "Dietitian Specialist",
    Nationality: "Saudi",
    Qualification: ["Bachelor Degree of Clinical Nutrition"],
    Experience: "6 Month",
    position: "Dietitian Specialist",
    License: ["Certified Diabetes Education for diabetes Center"],
    department: ["dietitian"],
    search: "Dietitian",
    searchid: ["61dc0c29b24354b161efe870"],
    skills: [
      "Slimming and fitness programs",
      "Obesity programs",
      "Monitor the nutritional status of patients",
      "Follow-up of the nutritional status of the patient after the operations",
    ],
    skillsar: [
      "Slimming and fitness programs",
      "Obesity programs",
      "Monitor the nutritional status of patients",
      "Follow-up of the nutritional status of the patient after the operations",
    ],
    mobno: "+00 0000 0000 00",
    email: "roberto@medwise.com",
    linkto: "Abeer_Alotaibi",
  },
  {
    imgUrl: "/assets/dr/maledoc.png",
    name: "Dr. Abeer Alotaibi",
    namear: "	د. عبير العتيبي",
    positionar: "	خبيرة تغذية",
    Nationality: "السعودية",
    Qualification: ["درجة البكالوريوس في التغذية العلاجية"],
    Experience: "6 شهور",
    position: "Dietitian Specialist",
    License: ["التثقيف المعتمد لمرض السكري لمركز السكري"],
    department: ["dietitian"],
    search: "Dietitian",
    searchid: ["61dc0c29b24354b161efe870"],
    skills: [
      "Slimming and fitness programs",
      "Obesity programs",
      "Monitor the nutritional status of patients",
      "Follow-up of the nutritional status of the patient after the operations",
    ],
    skillsar: [
      " برامج التخسيس واللياقة البدنية",
      " برامج السمنة",
      " مراقبة الحالة الغذائية للمرضى",
      "متابعة الحالة الغذائية للمريض بعد العمليات",
    ],
    mobno: "+00 0000 0000 00",
    email: "roberto@medwise.com",
    linkto: "Abeer_Alotaibi",
  },
];
export default { del };
