export const demoDatas = [
    {
        imgUrl: "/assets/real/14.png",
        name: "Dr. Eman Radwan",
        positionar: "	اخصائية نفسية",
        namear: "	د. ايمان رضوان",
        Nationality: "Egyptian",
        Qualification: "Master's degree in Psychiatry and neurology",
        Experience: "47 years",
        position: "Neuru Psychiatric Specialist ",
        department: ["neuro", "pshyciatric"],
        search: "Psychiatric Neuro",
        skills: [
            "Psychiatric analysis",
            "Personality disorders",
            "Mood disturbances and anxiety",
            "eating disorders",
            "sexual function disorders",
            "Adolescent and child disorders such as autism",
            "Language expression disorders, hyperactivity and learning difficulties",
        ],
        skillsar: [
            "	التحليل النفسي",
            "اضطرابات الشخصية",
            "	اضطرابات المزاج والقلق",
            "اضطرابات الأكل",
            "اضطرابات الوظيفة الجنسية",
            "اضطرابات المراهقين والأطفال مثل التوحد",
            "اضطرابات التعبير اللغوي وفرط النشاط وصعوبات التعلم",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Eman_Radwan",
    },
    {
        imgUrl: "/assets/real/15.png",
        name: "Dr. Attif Bassas",
        namear: "	د . عاطف بصاص",
        positionar: "	استشاري الجراحة العامة والاورام وجراحات السمنة",
        Nationality: "Saudi",
        Qualification: "PhD in general surgery At the Royal Jordanian College",
        Experience: "30+ years",
        position: "Bariatric Surgeon and General Specialist Surgeon",
        department: ["bariatic", "general_surgeon"],
        search: "Bariatic Surgery",
        License: [
            "World Obesity Association (IFSD) - American Society of Hepatology",
            "Followership of the Royal College of Surgeons in Ireland",
        ],
        skills: [
            "Tumor operations",
            "All types of obesity operations (re-obesity and morbid obesity)",
            "Gastric Bypass",
            "Gastric Banding",
            "Gastrectomy Sleeve ",
            "Laparoscopic sleeve gastrectomy",
            "SADI operation",
            "SASI process",
            "Oncology surgery",
            "General surgeries",
            "Mini gastric bypass",
        ],
        skillsar: [
            "	عمليات الورم",
            "عمليات السمنة بأنواعها (إعادة السمنة والسمنة المفرطة)",
            "	تحويل مسار المعدة",
            "	ربط المعدة",
            "	تكميم المعدة",
            "	تكميم المعدة بالمنظار",
            "	عملية SADI",
            "	عملية الساسي",
            "	جراحة الأورام",
            "	الجراحات العامة",
            "	المجازة المعدية المصغرة",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Attif_Bassas",
    },
    {
        imgUrl: "/assets/real/5.png",
        name: "Dr. Rehab Ammar",
        namear: "	د. رحاب عمار",
        positionar: "	اخصائية جلدية",
        Nationality: "Egyptian",
        Qualification:
            "Bachelor Degree in general surgery ( Dermatology and cosmetology) ",
        Experience: "9 years",
        position: "Dermatology resident",
        department: ["dermatology"],
        search: "Dermatology and Cosmetology",
        skills: [
            "Dermatopathology ",
            "Peeling( Chemical Type)",
            "Cosmetology",
            "PRP Plastic for hair removal",
            "Acne treatment",
            "Skin diseases",
            "Hyperpigmentation",
        ],
        skillsar: [
            "	الأمراض الجلدية",
            "	التقشير (النوع الكيميائي)",
            "(التجميل)",
            "PRP بلاستيك لإزالة الشعر",
            "علاج حب الشباب",
            "أمراض الجلد",
            " فرط تصبغ",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Rehab_Ammar",
    },
    {
        imgUrl: "/assets/real/13.png",
        name: "Dr. Mamdouh Oun Alsoud",
        namear: "	د. ممدوح عيون السود",
        positionar: "	استشاري جراحة عامة ومناظير",
        Nationality: "Syrian",
        Qualification: "Board in General Surgeries",
        Experience: "9 years",
        position: " Head of General Surgery and OR",
        department: ["or", "general_surgeon"],
        search: "General Surgery",
        License: ["Jordanian Board and Sweden Board"],
        skills: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        skillsar: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mamdouh_Oun_Alsoud",
    },
    {
        imgUrl: "/assets/real/7.png",
        name: "Dr. Asma Salem",
        namear: "	د. أسماء سالم",
        positionar: "	استشارية نساء وولادة",
        Nationality: "Yemeni",
        Qualification: "MBBS",
        Experience: " 15 years",
        position: "Consultant Gynecology and Obstetrics",
        department: ["obgyna"],
        search: "ob/Gyne",
        License: [
            "Jordanian Board on obstetric and Gynecology",
            "Arab Board on obstetrics and Gynecology",
            "Diploma and fellowship in FMAS World laparoscopy hospital india",
        ],
        skills: [
            "Caesarian section, extended Episiotomies ",
            "Complicated Genital tract tears",
            "Repair of Cervical tears",
            "Hysterectomies and Vaginal repair",
            "Cyst and laparoscopic Surgeries",
            "Management Postpartum Hemorrhage",
            "Surgical Disturbed ectopic pregnancy",
            "Distortion of ovarian cyst both through laparoscopic and abdominally",
            "Infertility",
        ],
        skillsar: [
            "العملية القيصرية.",
            "تمزق الجهاز التناسلي المعقد",
            "إصلاح تمزقات عنق الرحم",
            "استئصال الرحم وإصلاح المهبل",
            "جراحات الكيس والجراحة بالمنظار",
            "إدارة النزف التالي للوضع",
            "اضطراب الحمل خارج الرحم",
            "تشوه كيس المبيض سواء عن طريق المنظار أو البطن",
            "العقم",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Asma_Salem",
    },
    {
        imgUrl: "/assets/dr/femaledoc.png",
        name: "Dr. Somaya Abbas",
        namear: "	د. سمية عباس",
        positionar: "	استشارية نساء وولادة",
        Nationality: "Sudanese",
        Qualification: "Clinical Phd in Obstetrics and Gynecology",
        Experience: " 16 years",
        position: "Consultant Gynecology and Obstetrics",
        department: ["obgyna"],
        search: "ob/Gyne",
        skills: [
            "Pregnancy diagnoses and pregnancy Care",
            "Birth delivery and Surgical delivery",
            "Ultrasound",
        ],
        skillsar: [
            "تشخيص الحمل ورعاية الحمل",
            "الولادة والولادة الجراحية",
            "الموجات فوق الصوتية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Somaya_Abbas",
    },

    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Hansa Diyab",
        namear: "	د. حسناء دياب",
        positionar: "	اخصائية عيون",
        Nationality: "Egyptian",
        Qualification: "MSC Ophthalmology and bachelor medical and surgery",
        Experience: "15+ years",
        position: "Ophthalmology Specialist",
        department: ["ophthalmology"],
        search: "Ophthalmology",
        skills: [
            "Ophthalmoscope",
            "Retino-scope",
            "Refraction",
            "Surgical Treatment of ophthalmology",
            "Conjunctiva Cyst Removal",
            "Corneal Statues",
            "Wound Stutters",
            "Anterior Segment examination and treatment",
            "Squint Follow up diagnoses and surgery",
        ],
        skillsar: [
            "	منظار العين",
            "	منظار ريتينو",
            "	الانكسار العيون",
            "	العلاج الجراحي لطب العيون",
            "	إزالة كيس الملتحمة",
            "	تماثيل القرنية",
            "	الجروح التعتعة",
            "	فحص وعلاج الجزء الأمامي للعين",
            "	متابعة تشخيص وجراحة الحول",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Hansa_Diyab",
    },
    {
        imgUrl: "/assets/real/4.png",
        name: "Dr. Malek Hassan",
        namear: "	د. مالك حسن",
        positionar: "	طبيب عام",
        Nationality: "Syrian",
        Qualification: "Bachelor Degree in general Surgery ",
        Experience: "27 years",
        position: "General Practitioner (Head of ER department)",
        department: ["er"],
        search: "General Surgery",
        skills: [
            "Critical cases ",
            "Sutures",
            "Fever",
            "Common Illness",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
            "Hyperlipidemia",
        ],
        skillsar: [
            "	الحالات الحرجة",
            "	الغرز",
            "	الحمى",
            "	المرض المشترك",
            "	الصدمة",
            "	ارتفاع ضغط الدم",
            "	مرض السكري",
            "	فرط شحميات الدم",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Malek_Hassan",
    },
    {
        imgUrl: "/assets/real/11.png",
        name: "Dr. Abdulfatah Ali",
        namear: "	د. عبد اللطيف علي",
        positionar: "	استشاري انف واذن وحنجرة",
        Nationality: "Egyptian",
        Qualification: " Fellowship of the Royal College of Surgery",
        Experience: "42 years",
        position: "ENT Consultant",
        License: ["Membership of the American Nose and Throat Association"],
        department: ["ENT"],
        search: "ENT(Ear, Nose & Throat)",
        skills: [
            "Sinus view surgeries",
            "Diagnose ENT children's problems",
            "Diagnosis of hearing impaired children",
            "Special operations for snoring and sleep diseases",
            "Endoscopy of the upper respiratory tract and esophagus",
            "Laser and radiofrequency surgeries",
            "Microscopic ear operations",
            "Laryngoscopy ",
            "Flexible Nasoendoscopy",
            "Audiometer",
        ],
        skillsar: [
            "جراحات عرض الجيوب الأنفية",
            "تشخيص مشاكل الأطفال في الأنف والأذن والحنجرة",
            "تشخيص الأطفال ضعاف السمع",
            "عمليات خاصة لأمراض الشخير والنوم",
            "مناظير الجهاز التنفسي العلوي والمريء",
            "جراحات الليزر والترددات الراديوية",
            "عمليات الأذن المجهرية",
            "تنظير الحنجرة",
            "تنظير الأنف المرن",
            "مقياس السمع",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abdulfatah_Ali",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Abeer Alotaibi",
        namear: "	د. عبير العتيبي",
        positionar: "	خبيرة تغذية",
        Nationality: "Saudi",
        Qualification: "Bachelor Degree of Clinical Nutrition",
        Experience: "6 Month",
        position: "Dietitian Specialist",
        License: ["Certified Diabetes Education for diabetes Center"],
        department: ["dietitian"],
        search: "Dietitian",
        skills: [
            "Slimming and fitness programs",
            "Obesity programs",
            "Monitor the nutritional status of patients",
            "Follow-up of the nutritional status of the patient after the operations",
        ],
        skillsar: [
            " برامج التخسيس واللياقة البدنية",
            " برامج السمنة",
            " مراقبة الحالة الغذائية للمرضى",
            "متابعة الحالة الغذائية للمريض بعد العمليات",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abeer_Alotaibi",
    },
    {
        imgUrl: "/assets/real/9.png",
        name: "Dr. Saleh Eid",
        namear: "	د. صالح عيد",
        positionar: "	اخصائي جراحة عامة",
        Nationality: "Egyptian",
        Qualification: "Bachelor in Medicine and surgery",
        Experience: "36 Years",
        position: "General Surgeon Specialist",
        department: ["general_surgeon"],
        search: "General Surgery",
        skills: [
            "hernia, appendix",
            "Hemorrhoids",
            "anal fissure",
            "circumcision",
        ],
        skillsar: ["فتق ، الملحق", "البواسير", "الشق الشرجي", "الختان"],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Saleh_Eid",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Mohammed Alnather",
        namear: "	د. محمد الناظر",
        positionar: "	اخصائي قلب",
        Nationality: "Egyptian",
        Qualification: "Master Degree in Cardiology",
        Experience: "44 Years",
        position: " Cardiologist and Internal Medicine Consultant",
        department: ["cardiologist"],
        search: "Cardiologist",
        License: ["internal medicine British followership"],
        skills: [
            "Internal medicine Cases",
            "Cardio Vascular System",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
        ],
        skillsar: [
            "حالات الطب الباطني",
            "نظام القلب والأوعية الدموية",
            "الصدمة",
            " ارتفاع ضغط الدم",
            "مرض السكري",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alnather",
    },
    {
        imgUrl: "/assets/real/12.png",
        name: "Dr. Abdulrahman Alsouify",
        namear: "	د. عبدالرحمن السويفي",
        positionar: "	اخصائي جراحة المسالك البولية والتناسلية",
        Nationality: "Egyptian",
        Qualification: "Master degree in Urology",
        Experience: "14 Years",
        position: "Registrar Urology - Medical Director",
        department: ["urology"],
        search: "Urology",
        skills: [
            "Prostate diseases and infections",
            "Infertility and delayed childbearing",
            "Testicular study",
            "Congenital defects of the cell and penis",
            "Urogenital infections",
            "Kidney, ureter, bladder stones",
        ],
        skillsar: [
            "أمراض والتهابات البروستاتا",
            "العقم وتأخر الإنجاب",
            "دراسة الخصية",
            "العيوب الخلقية في الخلية والقضيب",
            "التهابات الجهاز البولي التناسلي",
            "حصوات الكلى والحالب والمثانة",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abdulrahman_Alsouify",
    },
    {
        imgUrl: "/assets/real/8.png",
        name: "Dr. Dania Bawadkji",
        namear: "	د. دنيا باوادكجي",
        positionar: "	طبيبة اسنان",
        Nationality: "Syrian",
        Qualification: "Bachelor's degree in dentistry",
        Experience: "3 Years",
        position: "General Dentist",
        department: ["dentist"],
        search: "Dentistry",
        skills: [
            "Periapical x-ray, panoramic , CT scan.",
            "Removable prosthodontics.",
            "Fixed prosthodontics",
            "Gum treatment",
            "Orthodontics",
            "Cosmetic fillings",
            "Root Canal",
            "Filling",
            "Denture",
            "General and surgical Extraction",
        ],
        skillsar: [
            "الأشعة السينية ، بانورامية ، الأشعة المقطعية.",
            "التركيبات القابلة للإزالة.",
            "التركيبات الثابتة.",
            "علاج اللثة",
            "تقويم الأسنان",
            "حشوات تجميلية",
            "قناة الجذر",
            "الحشوة",
            "طقم أسنان",
            "الخلع العام والجراحي",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Dania_Bawadkji",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Alaa Mohammed",
        namear: "	د. علاء محمد",
        positionar: "	اخصائي عظام",
        Nationality: "Egyptian",
        Qualification: "Master Degree",
        Experience: "10 Years",
        position: "Orthopedics Specialist",
        department: ["orthopedics"],
        search: "Orthopedics",
        skills: [
            "Joint Diseases",
            "Tumors",
            "Trauma closed and open reduction ",
            "Local joint Injections",
            "Plaster cast (POP)",
            "Tendon repair ",
            "Arthroplasty",
            "Sports Injury",
        ],
        skillsar: [
            "أمراض المفاصل",
            "الأورام",
            "الصدمة مغلقة وفتح الحد",
            "حقن المفاصل المحلية",
            "(POP) الجبس ",
            "إصلاح الأوتار",
            "تقويم المفاصل",
            "الإصابات الرياضية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Alaa_Mohammed",
    },
    {
        imgUrl: "/assets/real/2.png",
        name: "Dr. Eman Mohammed",
        namear: "	د. ايمان محمود",
        positionar: "	اخصائية اطفال",
        Nationality: "Chinese",
        Qualification: "",
        Experience: "",
        position: "Pediatric Specialist",
        department: ["pediatrics"],
        search: "pediatric",
        skills: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
        ],
        skillsar: [
            "أمراض الجهاز الهضمي",
            "مرض الرئة (الربو)",
            "ومضات الاكتئاب",
            "الأطفال حديثي الولادة",
            "الأنفلونزا المعوية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Eman_Mohammed",
    },
    {
        imgUrl: "/assets/real/3.png",
        name: "Dr. Mohammed Alsamamni",
        namear: "	د. محمد السماني",
        positionar: "	اخصائي علاج طبيعي",
        Nationality: "Sudanese",
        Qualification: "Bachelor Degree in Physiotherapy",
        Experience: "",
        position: "Physiotherapist Specialist ",
        department: ["physiotherapist"],
        License: ["Czech Republic Studies"],
        search: "Physiotherapy",
        skills: [
            "Treating orthopedic and neurological diseases",
            "Sports injury rehabilitation",
            "thromboembolism treatment",
            "Rehabilitation of handicapped children",
            "Facial nerve treatment",
        ],
        skillsar: [
            "علاج أمراض العظام والجهاز العصبي",
            "تأهيل الإصابات الرياضية",
            "علاج الجلطات الدموية",
            "تأهيل الأطفال المعوقين",
            "علاج عصب الوجه",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alsamamni",
    },
    {
        imgUrl: "/assets/real/10.png",
        name: "Dr. Ahmed Ali",
        namear: "	د. أحمد علي",
        positionar: "	استشاري باطنية وجهاز هضمي",
        Nationality: "Egyptian",
        Qualification: "PhD in internal medicine",
        Experience: "30 Years",
        position:
            "Consultant and Professor of internal Medicine / Head of Internal Medicine Dept.",
        department: ["internalmeds"],
        search: "",
        skills: [
            "Chest allergy",
            "High blood pressure",
            "Chronic diabetes",
            "Gastrointestinal diseases",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
            "Respiratory system",
            "Digestive system",
        ],
        skillsar: [
            "حساسية الصدر",
            "ارتفاع ضغط الدم",
            "مرض السكري المزمن",
            "أمراض الجهاز الهضمي",
            "تنظير البطن التشخيصي",
            "الجهاز التنفسي",
            "الجهاز الهضمي",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ahmed_Ali",
    },
    {
        imgUrl: "/assets/real/6.png",
        name: "Dr. Ibrahim Rushdi",
        namear: "	د. إبراهيم رشدي",
        positionar: "	اخصائي اطفال",
        Nationality: "Egyptian",
        Qualification: "Master's degree in pediatrics",
        Experience: "30 Years",
        position: "Head of the Department of Pediatrics and Neonatology",
        department: ["pediatrics"],
        search: "pediatric",
        License: [
            "Membership of the Jordanian Medical Council",
            "Colon and gastrointestinal tumors",
            "Doctors Membership ",
        ],
        skills: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
        ],
        skillsar: [
            "أمراض الجهاز الهضمي",
            " مرض الرئة (الربو)",
            "ومضات الاكتئاب",
            "الأطفال حديثي الولادة",
            "الأنفلونزا المعوية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ibrahim_Rushdi",
    },
    {
        imgUrl: "/assets/real/1.png",
        name: "Dr. Ahmed Nader",
        namear: "	د. أحمد نادر",
        positionar: "	اخصائي اول جراحة عامة",
        Nationality: "Palastnian",
        Qualification: "Jordanian Board of General Surgery",
        Experience: "7 Years",
        position: "Senior registrar General Surgery",
        department: ["general_surgeon"],
        search: "General Surgery",
        License: [
            "Membership of the Jordanian Medical Council",
            "Colon and gastrointestinal tumors",
            "Doctors Membership",
        ],
        skills: [
            "Appendectomy ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        skillsar: [
            "استئصال الزائدة الدودية (بالمنظار والفتح)",
            "استئصال الثدي",
            "جراحة المناظير",
            " التدخل الأمريكي الموجه",
            "FNAC",
            "تنظير البطن التشخيصي",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ahmed_Nader",
    },
];

export default { demoDatas };
