export const demoData = [
    {
        imgUrl: "/assets/real/14.png",
        name: "Dr. Eman Radwan",
        positionar: "Nuoru Phsycstric Specialist ",
        namear: "	Dr. Eman Radwan",
        Nationality: "Egyptian",
        Qualification: "Master's degree in Psychiatry and neurology",
        Experience: "14 years",
        position: "Neuru Psychiatric Specialist ",
        department: ["neuro", "pshyciatric"],
        search: "Psychiatric Neuro",
        searchid: ["61dc0c29b24354b161efe874", "61dc0c29b24354b161efe875"],

        skills: [
            "Psychiatric analysis",
            "Personality disorders",
            "Mood disturbances and anxiety",
            "eating disorders",
            "sexual function disorders",
            "Adolescent and child disorders such as autism",
            "Language expression disorders, hyperactivity and learning difficulties",
        ],
        skillsar: [
            "Psychiatric analysis",
            "Personality disorders",
            "Mood disturbances and anxiety",
            "eating disorders",
            "sexual function disorders",
            "Adolescent and child disorders such as autism",
            "Language expression disorders, hyperactivity and learning difficulties",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Eman_Radwan",
    },
    {
        imgUrl: "/assets/real/15.png",
        name: "Dr. Attif Bassas",
        namear: "Dr. Attif Bassas",
        positionar: "Bariatric Surgeon and General Specialist Surgeon",
        Nationality: "Saudi",
        Qualification: "PhD in general surgery At the Royal Jordanian College",
        Experience: "30+ years",
        position: "Bariatric Surgeon and General Specialist Surgeon",
        department: ["bariatic", "general_surgeon"],
        search: "Bariatic Surgery",
        searchid: ["61dc0c29b24354b161efe876"],
        License: [
            "World Obesity Association (IFSD) - American Society of Hepatology",
            "Followership of the Royal College of Surgeons in Ireland",
        ],
        skills: [
            "Tumor operations",
            "All types of obesity operations (re-obesity and morbid obesity)",
            "Gastric Bypass",
            "Gastric Banding",
            "Gastrectomy Sleeve ",
            "Laparoscopic sleeve gastrectomy",
            "SADI operation",
            "SASI process",
            "Oncology surgery",
            "General surgeries",
            "Mini gastric bypass",
        ],
        skillsar: [
            "Tumor operations",
            "All types of obesity operations (re-obesity and morbid obesity)",
            "Gastric Bypass",
            "Gastric Banding",
            "Gastrectomy Sleeve ",
            "Laparoscopic sleeve gastrectomy",
            "SADI operation",
            "SASI process",
            "Oncology surgery",
            "General surgeries",
            "Mini gastric bypass",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Attif_Bassas",
    },
    {
        imgUrl: "/assets/real/5.png",
        name: "Dr. Rehab Ammar",
        namear: "Dr. Rehab Ammar",
        positionar: "Dermatology resident",
        Nationality: "Egyptian",
        Qualification:
            "Bachelor Degree in general surgery ( Dermatology and cosmetology) ",
        Experience: "9 years",
        position: "Dermatology resident",
        department: ["dermatology"],
        search: "Dermatology and Cosmetology",
        searchid: ["61dc0c29b24354b161efe871"],
        skills: [
            "Dermatopathology ",
            "Peeling( Chemical Type)",
            "Cosmetology",
            "PRP Plastic for hair removal",
            "Acne treatment",
            "Skin diseases",
            "Hyperpigmentation",
        ],
        skillsar: [
            "Dermatopathology ",
            "Peeling( Chemical Type)",
            "Cosmetology",
            "PRP Plastic for hair removal",
            "Acne treatment",
            "Skin diseases",
            "Hyperpigmentation",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Rehab_Ammar",
    },
    {
        imgUrl: "/assets/real/13.png",
        name: "Dr. Mamdouh Oun Alsoud",
        namear: "Dr. Mamdouh Oun Alsoud",
        positionar:
            "Surgery & Laparoscopic Consultant and Head of General Surgery and OR",
        Nationality: "Syrian",
        Qualification: "Board in General Surgeries",
        Experience: "9 years",
        position: " Head of General Surgery and OR",
        department: ["or", "general_surgeon"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        License: ["Jordanian Board and Sweden Board"],
        skills: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        skillsar: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mamdouh_Oun_Alsoud",
    },
    {
        imgUrl: "/assets/real/7.png",
        name: "Dr. Asma Salem",
        namear: "Dr. Asma Salem Bahartha",
        positionar: "Gynecology and Obstetrics Consultant",
        Nationality: "Yemeni",
        Qualification: "MBBS",
        Experience: " 16 years and more",
        position: "Consultant Gynecology and Obstetrics",
        department: ["obgyna"],
        search: "ob/Gyne",
        searchid: ["61dc0c29b24354b161efe86b"],
        License: [
            "Jordanian Board on obstetric and Gynecology",
            "Arab Board on obstetrics and Gynecology",
            "Diploma and fellowship in FMAS World laparoscopy hospital india",
        ],
        skills: [
            "Caesarian section, extended Episiotomies ",
            "Complicated Genital tract tears",
            "Repair of Cervical tears",
            "Hysterectomies and Vaginal repair",
            "Cyst and laparoscopic Surgeries",
            "Management Postpartum Hemorrhage",
            "Surgical Disturbed ectopic pregnancy",
            "Distortion of ovarian cyst both through laparoscopic and abdominally",
            "Infertility",
        ],
        skillsar: [
            "Caesarian section, extended Episiotomies ",
            "Complicated Genital tract tears",
            "Repair of Cervical tears",
            "Hysterectomies and Vaginal repair",
            "Cyst and laparoscopic Surgeries",
            "Management Postpartum Hemorrhage",
            "Surgical Disturbed ectopic pregnancy",
            "Distortion of ovarian cyst both through laparoscopic and abdominally",
            "Infertility",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Asma_Salem",
    },
    {
        imgUrl: "/assets/dr/femaledoc.png",
        name: "Dr. Somaya Abbas",
        namear: "Dr. Somaya Abbas",
        positionar: "Gynecology and Obstetrics Consultant",
        Nationality: "Sudanese",
        Qualification: "Clinical Phd in Obstetrics and Gynecology",
        Experience: " 16 years",
        position: "Consultant Gynecology and Obstetrics",
        department: ["obgyna"],
        search: "ob/Gyne",
        searchid: ["61dc0c29b24354b161efe86b"],
        skills: [
            "Pregnancy diagnoses and pregnancy Care",
            "Birth delivery and Surgical delivery",
            "Ultrasound",
        ],
        skillsar: [
            "Pregnancy diagnoses and pregnancy Care",
            "Birth delivery and Surgical delivery",
            "Ultrasound",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Somaya_Abbas",
    },

    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Hansa Diyab",
        namear: "Dr. Hansa Diyab",
        positionar: "Ophthalmology Specialist",
        Nationality: "Egyptian",
        Qualification: "MSC Ophthalmology and surgery",
        Experience: "15+ years",
        position: "Ophthalmology Specialist",
        department: ["ophthalmology"],
        search: "Ophthalmology",
        searchid: ["61dc0c29b24354b161efe86c"],
        skills: [
            "Ophthalmoscope",
            "Retino-scope",
            "Refraction",
            "Surgical Treatment of ophthalmology",
            "Conjunctiva Cyst Removal",
            "Corneal Statues",
            "Wound Stutters",
            "Anterior Segment examination and treatment",
            "Squint Follow up diagnoses and surgery",
        ],
        skillsar: [
            "Ophthalmoscope",
            "Retino-scope",
            "Refraction",
            "Surgical Treatment of ophthalmology",
            "Conjunctiva Cyst Removal",
            "Corneal Statues",
            "Wound Stutters",
            "Anterior Segment examination and treatment",
            "Squint Follow up diagnoses and surgery",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Hansa_Diyab",
    },
    {
        imgUrl: "/assets/real/4.png",
        name: "Dr. Malek Hassan",
        namear: "Dr. Malek Hassan",
        positionar: "General Practitioner (Head of ER department)",
        Nationality: "Syrian",
        Qualification: "Bachelor Degree in Medicine and  general Surgery",
        Experience: "27 years",
        position: "General Practitioner (Head of ER department)",
        department: ["er"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        skills: [
            "Critical cases ",
            "Sutures",
            "Fever",
            "Common Illness",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
            "Hyperlipidemia",
        ],
        skillsar: [
            "Critical cases ",
            "Sutures",
            "Fever",
            "Common Illness",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
            "Hyperlipidemia",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Malek_Hassan",
    },
    {
        imgUrl: "/assets/real/11.png",
        name: "Dr. Abdulfatah Ali",
        namear: "Dr. Abdulfatah Ali",
        positionar: "Ear, Nose and Throat Consultant",
        Nationality: "Egyptian",
        Qualification: " Fellowship of the Royal College of Surgery",
        Experience: "30 years and more",
        position: "ENT Consultant",
        License: ["Membership of the American Nose and Throat Association"],
        department: ["ENT"],
        search: "ENT(Ear, Nose & Throat)",
        searchid: ["61dc0c29b24354b161efe878"],
        skills: [
            "Sinus view surgeries",
            "Diagnose ENT children's problems",
            "Diagnosis of hearing impaired children",
            "Special operations for snoring and sleep diseases",
            "Endoscopy of the upper respiratory tract and esophagus",
            "Laser and radiofrequency surgeries",
            "Microscopic ear operations",
            "Laryngoscopy ",
            "Flexible Nasoendoscopy",
            "Audiometer",
        ],
        skillsar: [
            "Sinus view surgeries",
            "Diagnose ENT children's problems",
            "Diagnosis of hearing impaired children",
            "Special operations for snoring and sleep diseases",
            "Endoscopy of the upper respiratory tract and esophagus",
            "Laser and radiofrequency surgeries",
            "Microscopic ear operations",
            "Laryngoscopy ",
            "Flexible Nasoendoscopy",
            "Audiometer",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abdulfatah_Ali",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Abeer Alotaibi",
        namear: "Dr. Abeer Alotaibi",
        positionar: "Dietitian Specialist",
        Nationality: "Saudi",
        Qualification: "Bachelor Degree of Clinical Nutrition",
        Experience: "6 Month",
        position: "Dietitian Specialist",
        License: ["Certified Diabetes Education for diabetes Center"],
        department: ["dietitian"],
        search: "Dietitian",
        searchid: ["61dc0c29b24354b161efe870"],
        skills: [
            "Slimming and fitness programs",
            "Obesity programs",
            "Monitor the nutritional status of patients",
            "Follow-up of the nutritional status of the patient after the operations",
        ],
        skillsar: [
            "Slimming and fitness programs",
            "Obesity programs",
            "Monitor the nutritional status of patients",
            "Follow-up of the nutritional status of the patient after the operations",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abeer_Alotaibi",
    },
    {
        imgUrl: "/assets/real/9.png",
        name: "Dr. Saleh Eid",
        namear: "Dr. Saleh Eid",
        positionar: "General Surgeon Specialist",
        Nationality: "Egyptian",
        Qualification: "Diploma in General Surgery",
        Experience: "36 Years",
        position: "General Surgeon Specialist",
        department: ["general_surgeon"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        skills: [
            "hernia, appendix",
            "Hemorrhoids",
            "anal fissure",
            "circumcision",
        ],
        skillsar: [
            "hernia, appendix",
            "Hemorrhoids",
            "anal fissure",
            "circumcision",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Saleh_Eid",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Mohammed Alnather",
        namear: "Dr. Mohammed Alnather",
        positionar: "Cardiologist and Internal Medicine Consultant",
        Nationality: "Egyptian",
        Qualification: "Master Degree in Cardiology",
        Experience: "44 Years",
        position: " Cardiologist and Internal Medicine Consultant",
        department: ["cardiologist", "internalmeds"],
        search: "Cardiologist",
        searchid: ["61dc0c29b24354b161efe86e"],
        License: ["internal medicine British followership"],
        skills: [
            "Internal medicine Cases",
            "Cardio Vascular System",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
        ],
        skillsar: [
            "Internal medicine Cases",
            "Cardio Vascular System",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alnather",
    },
    {
        imgUrl: "/assets/real/12.png",
        name: "Dr. Abdulrahman Alsouify",
        namear: "Dr. Abdulrahman Alsouify",
        positionar: "Urology and Andrology specialist",
        Nationality: "Egyptian",
        Qualification:
            "Master degree in Urology and Andrology (Ain-Shams University)",
        Experience: "14 Years",
        position: "Registrar Urology - Medical Director",
        department: ["urology"],
        search: "Urology",
        searchid: ["61dc0c29b24354b161efe873"],
        skills: [
            "Prostate diseases and infections",
            "Infertility and delayed childbearing",
            "Testicular study",
            "Congenital defects of the cell and penis",
            "Urogenital infections",
            "Kidney, ureter, bladder stones",
        ],
        skillsar: [
            "Prostate diseases and infections",
            "Infertility and delayed childbearing",
            "Testicular study",
            "Congenital defects of the cell and penis",
            "Urogenital infections",
            "Kidney, ureter, bladder stones",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abdulrahman_Alsouify",
    },
    {
        imgUrl: "/assets/real/8.png",
        name: "Dr. Dania Bawadkji",
        namear: "Dr. Dania Bawadkji",
        positionar: "General Dentist",
        Nationality: "Syrian",
        Qualification: "Bachelor's degree in dentistry",
        Experience: "3 Years",
        position: "General Dentist",
        department: ["dentist"],
        search: "Dentistry",
        searchid: ["61dc0c29b24354b161efe86f"],
        skills: [
            "Periapical x-ray, panoramic, CT scan",
            "Excision biopsy",
            "Jaw joint treatment",
            "Removable prosthodontics",
            "Children's dental treatment",
            "Fixed prosthodontics",
            "Gum treatment",
            "Orthodontics",
            "Cosmetic fillings",
            "Root Canal",
            "Filling",
            "General and surgical Extraction",
        ],
        skillsar: [
            "Psychiatric analysis",
            "Personality disorders",
            "Mood disturbances and anxiety",
            "eating disorders",
            "sexual function disorders",
            "Adolescent and child disorders such as autism",
            "Language expression disorders, hyperactivity and learning difficulties",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Dania_Bawadkji",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Alaa Mohammed",
        namear: "Dr. Alaa Mohammed",
        positionar: "Orthopedics Specialist",
        Nationality: "Egyptian",
        Qualification: "Master Degree In Orthopedics",
        Experience: "3 Years",
        position: "Orthopedics Specialist",
        department: ["orthopedics"],
        search: "Orthopedics",
        searchid: ["61dc0c29b24354b161efe872"],
        skills: [
            "Joint Diseases",
            "Tumors",
            "Trauma closed and open reduction ",
            "Local joint Injections",
            "Plaster cast (POP)",
            "Tendon repair ",
            "Arthroplasty",
            "Sports Injury",
        ],
        skillsar: [
            "Joint Diseases",
            "Tumors",
            "Trauma closed and open reduction ",
            "Local joint Injections",
            "Plaster cast (POP)",
            "Tendon repair ",
            "Arthroplasty",
            "Sports Injury",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Alaa_Mohammed",
    },
    {
        imgUrl: "/assets/real/2.png",
        name: "Dr. Eman Mohammed",
        namear: "Dr. Eman Mohammed",
        positionar: "Pediatric Specialist",
        Nationality: "Chinese",
        Qualification: "Saudi Board Pediatric registrar",
        Experience: "6 Years",
        position: "Pediatric Specialist",
        department: ["pediatrics"],
        search: "pediatric",
        searchid: ["61dc0c29b24354b161efe86a"],
        skills: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
        ],
        skillsar: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Eman_Mohammed",
    },
    {
        imgUrl: "/assets/real/3.png",
        name: "Dr. Mohammed Alsamamni",
        namear: "Dr. Mohammed Alsamamni",
        positionar: "Physiotherapist Specialist",
        Nationality: "Sudanese",
        Qualification: "Bachelor Degree in Physiotherapy",
        Experience: "30 years and more",
        position: "Physiotherapist Specielist ",
        department: ["physiotherapist"],
        License: ["Czech Republic Studies"],
        search: "Physiotherapy",
        searchid: ["61dc0c29b24354b161efe877"],
        skills: [
            "Treating orthopedic and neurological diseases",
            "Sports injury rehabilitation",
            "thromboembolism treatment",
            "Rehabilitation of handicapped children",
            "Facial nerve treatment",
        ],
        skillsar: [
            "Treating orthopedic and neurological diseases",
            "Sports injury rehabilitation",
            "thromboembolism treatment",
            "Rehabilitation of handicapped children",
            "Facial nerve treatment",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alsamamni",
    },
    {
        imgUrl: "/assets/real/10.png",
        name: "Dr. Ahmed Ali",
        namear: "Dr. Ahmed Ali",
        positionar:
            "Consultant and Professor of Internal Medicine / Head of Internal Medicine Dept.",
        Nationality: "Egyptian",
        Qualification: "PhD in internal medicine",
        Experience: "30 Years and more",
        position:
            "Consultant and Professor of Internal Medicine / Head of Internal Medicine Dept.",
        department: ["internalmeds"],
        search: "internalmeds",
        searchid: ["61de40bca391f298f2fa8a32"],
        skills: [
            "Chest allergy",
            "High blood pressure",
            "Chronic diabetes",
            "Gastrointestinal diseases",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
            "Respiratory system",
            "Digestive system",
            "Take samples from the liver",
        ],
        skillsar: [
            "Chest allergy",
            "High blood pressure",
            "Chronic diabetes",
            "Gastrointestinal diseases",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
            "Respiratory system",
            "Digestive system",
            "Take samples from the liver",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ahmed_Ali",
    },
    {
        imgUrl: "/assets/real/6.png",
        name: "Dr. Ibrahim Rushdi",
        namear: "Dr. Ibrahim Rushdi",
        positionar: "Head of the Department of Pediatrics and Neonatology",
        Nationality: "Egyptian",
        Qualification: "Master's degree in pediatrics",
        Experience: "30 Years and more",
        position: "Head of the Department of Pediatrics and Neonatology",
        department: ["pediatrics"],
        search: "pediatric",
        searchid: ["61dc0c29b24354b161efe86a"],
        skills: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
            "Intestinal flu",
            "Malnutrition",
            "respiratory failure",
        ],
        skillsar: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
            "Intestinal flu",
            "Malnutrition",
            "respiratory failure",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ibrahim_Rushdi",
    },
    {
        imgUrl: "/assets/real/1.png",
        name: "Dr. Ahmed Nader",
        namear: "Dr. Ahmed Nader",
        positionar: "Senior registrar General Surgery",
        Nationality: "Palastnian",
        Qualification: "Jordanian Board of General Surgery",
        Experience: "7 Years",
        position: "Senior registrar General Surgery",
        department: ["general_surgeon"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        License: [
            "Membership of the Jordanian Medical Council",
            "Doctors Membership of Mutah University",
        ],
        skills: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        skillsar: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ahmed_Nader",
    },
    {
        imgUrl: "/assets/dr/femaledoc.png",
        name: "Dr. Moza ",
        namear: "Dr. Moza ",
        positionar: "Dermatology and cosmetic consultant",
        Nationality: "The United Arab Emirates",
        Qualification: "",
        Experience: " 20 years",
        position: "Dermatology and cosmetic consultant",
        department: ["dermatology"],
        search: "dermatology",
        searchid: [""],
        skills: ["Laser", "Botox", "fillers", "Plasma", "Cleansing "],
        skillsar: ["Laser", "Botox", "fillers", "Plasma", "Cleansing "],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "dr_mosa",
    },
];

export default { demoData };
