export const demodept =[
    { "value": "all", "label": "all" },
    { "value": "eman", "label": "eman" },
    { "value": "radiology", "label": "Radiology" },
    { "value": "physiotherapy", "label": "Physiotherapy" },
    { "value": "home-care", "label": "Home Care" },
    { "value": "operations", "label": "Operations" },
    { "value": "delivery", "label": "Delivery" },
    { "value": "or", "label": "OR" },
    { "value": "dermatology", "label": "Dermatology" },
    { "value": "pediatric", "label": "Pediatric" },
    { "value": "ob-gyna", "label": "OB-Gyna" },
    { "value": "ophthalmology", "label": "Ophthalmology" },
    { "value": "internal-medicine", "label": "Internal Medicine" },
    { "value": "dentistry", "label": "Dentistry" },
    { "value": "dietition", "label": "Dietition" },
    { "value": "surgery", "label": "Surgery" },
    { "value": "urology", "label": "Urology" },
    { "value": "cardiology", "label": "Cardiology" },
    { "value": "neuro", "label": "Neuro" },
    { "value": "phschiatric", "label": "Phschiatric" },
    { "value": "bariatric-surgery", "label": "Bariatric Surgery" }
]