export const demoClinic = [
    {
        name: "Pediatric",
        desc: "A paediatrician is a child's physician who provides not only medical care for children who are acutely or chronically ill but also preventive health services for healthy children.",
        imgurl: "assets/department/Pediatrics.png",
        linkto: "/clinics/pediatrics",
    },
    {
        name: "OB/Gyne",
        desc: "OB-GYNs also historically have more cultural competency training around gender based issues..",
        imgurl: "assets/department/ob.png",
        linkto: "/clinics/ob-gyne",
    },
    {
        name: "Ophthalmology",
        desc: "Ophthalmology is a branch of medicine dealing with the diagnosis, treatment and prevention of diseases of the eye and visual system.",
        imgurl: "assets/department/bones.png",
        linkto: "/clinics/ophthalmology",
    },
    {
        name: "Gastroenterology",
        desc: "Gastroenterology is a medical specialty dealing with the study of the digestive system and its disorders.",
        imgurl: "assets/department/gas.png",
        linkto: "/clinics/gastroenterology",
    },
    {
        name: "Cardiologist",
        desc: "The department of a hospital responsible for the provision of medical and surgical care to patients arriving at the hospital in need of immediate care.",
        imgurl: "assets/department/cardio.png",
        linkto: "/clinics/cardiologist",
    },
    // {
    //     name: "Internal Medicine Department",
    //     desc: "The department of a hospital responsible for the provision of medical and surgical care to patients arriving at the hospital in need of immediate care.",
    //     imgurl: "assets/department/cardio.png",
    //     linkto: "/clinics/internal-medicine",
    // },
    {
        name: "Dentistry",
        desc: "Dentistry, the profession concerned with the prevention and treatment of oral disease, including diseases of the teeth and supporting structures and diseases of the soft tissues of the mouth.",
        imgurl: "assets/department/dentist.png",
        linkto: "/clinics/dentistry",
    },
    {
        name: "Dietitian",
        desc: "The department of a hospital responsible for the provision of medical and surgical care to patients arriving at the hospital in need of immediate care.",
        imgurl: "assets/department/die.png",
        linkto: "/clinics/dietitian",
    },
    {
        name: "Dermatology and Cosmetology",
        desc: "Dermatology is the branch of medicine dealing with the skin. It is a speciality with both medical and surgical aspects.",
        imgurl: "assets/department/derma.png",
        linkto: "/clinics/dermatology",
    },
    {
        name: "Orthopedics",
        desc: "The department of a hospital responsible for the provision of medical and surgical care to patients arriving at the hospital in need of immediate care.",
        imgurl: "assets/department/ortho.png",
        linkto: "/clinics/orthopedics",
    },
    {
        name: "General Surgery",
        desc: "General surgery are deal with diseases involving the skin, breast, soft tissue, trauma, Peripheral artery disease and hernias.",
        imgurl: "assets/department/surgery.png",
        linkto: "/clinics/general-surgery",
    },
    {
        name: "Urology",
        desc: "Urology is a part of health care that deals with diseases of the male and female urinary tract (kidneys, ureters, bladder and urethra).",
        imgurl: "assets/department/Urology.png",
        linkto: "/clinics/urology",
    },
    {
        name: "Neuro",
        desc: "Neurology is the branch of medicine concerned with the study and treatment of disorders of the nervous system.",
        imgurl: "assets/department/neurology.png",
        linkto: "/clinics/neuro",
    },
    {
        name: "Psychiatric",
        desc: "Psychiatry is the branch of medicine focused on the diagnosis, treatment and prevention of mental, emotional and behavioral disorders.",
        imgurl: "assets/department/Pshyciatric.png",
        linkto: "/clinics/pshyciatric",
    },
    {
        name: "Bariatric Surgery",
        desc: "Bariatric surgery is an operation that is performed in order to help such individuals lose weight.",
        imgurl: "assets/department/Bariatic.png",
        linkto: "/clinics/bariatic-surgery",
    },
    {
        name: "Physiotherapy",
        desc: "Healthcare profession concerned with the assessment, maintenance, and restoration of the physical function.",
        imgurl: "assets/department/physio.png",
        linkto: "/clinics/physiotherapist",
    },
    {
        name: "ENT (Ear, Nose & Throat)",
        desc: "If you have a health problem with your head or neck, your doctor might recommend that you see an otolaryngologist.",
        imgurl: "assets/department/EarNoseThroat.png",
        linkto: "/clinics/ear-nose-throat",
    },
];
export default { demoClinic };
