export const demoDatas = [
    {
        imgUrl: "/assets/real/eman_radwan.png",
        name: "Dr. Eman Radwan",
        positionar: "	اخصائية نفسيةاخصائية نفسية وعصبية",
        namear: "	د. ايمان رضوان",
        Nationality: "المصرية",
        Qualification: ["درجة الماجستير في الطب النفسي وعلم الأعصاب"],
        Experience: "14 سنة",
        position: "Neuru Psychiatric Specialist ",
        department: ["neuro", "pshyciatric"],
        search: "Psychiatric Neuro",
        searchid: ["61dc0c29b24354b161efe874", "61dc0c29b24354b161efe875"],
        skills: [
            "Psychiatric analysis",
            "Personality disorders",
            "Mood disturbances and anxiety",
            "eating disorders",
            "sexual function disorders",
            "Adolescent and child disorders such as autism",
            "Language expression disorders, hyperactivity and learning difficulties",
        ],
        skillsar: [
            "	التحليل النفسي",
            "اضطرابات الشخصية",
            "	اضطرابات المزاج والقلق",
            "اضطرابات الأكل",
            "اضطرابات الوظيفة الجنسية",
            "اضطرابات المراهقين والأطفال مثل التوحد",
            "اضطرابات التعبير اللغوي وفرط النشاط وصعوبات التعلم",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Eman_Radwan",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        moid: "61dc0edbb24354b161f1730f",
        name: "Dr. Feras Alharbi",
        namear: "د. فراس الحربي",
        positionar: "استشاري مسالك بولية وتناسلية",
        Nationality: "سعودي",
        Qualification: [
            "البورد الفرنسي في جراحة المسالك البولية",
            "الزمالة الفرنسية في أورام المسالك البولية",
            "الزمالة الفرنسية في الجراحة الترميمية في المسالك البولية",
            "الزمالة الفرنسية في جراحة المناظير و الرجل الآلي في المسالك البولية",
        ],
        License: [
            "البورد الفرنسي في جراحة المسالك البولية",
            "الزمالة الفرنسية في أورام المسالك البولية",
            "الزمالة الفرنسية في الجراحة الترميمية في المسالك البولية",
            "الزمالة الفرنسية في جراحة المناظير و الرجل الآلي في المسالك البولية",
        ],
        Experience: "",
        position: "Urology and Andrology Conultant",
        department: ["urology"],
        search: "Urology",
        searchid: ["61dc0c29b24354b161efe86c"],
        skills: [
            "All Urinary Stones problems",
            "Prostate problems",
            "Urology cancers",
            "Urology infections",
            "Endourology procedures",
            "Laparoscopic and Robotic surgeries",
            "Infertility",
            "Male genital problems",
        ],
        skillsar: [
            "جميع حصوات الجهاز البولي",
            "مشاكل البروستات",
            "أورام و سرطانات المسالك البولية",
            "إلتهابات المسالك البولية",
            "العقم و أمراض الذكورة و الجهاز التناسلي في الذكور",
            "المناظير في جراحة المسالك البولية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Feras_Alharbi",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        moid: "61dc0edbb24354b161f1730f",
        name: "Dr. Mohammed Alnujaym",
        namear: "د. محمد عبدالله النجيم",
        positionar: "طبيب اسنان عام",
        Nationality: "سعودي",
        Qualification: [],
        License: ["بكالوريوس طب وجراحة الفم والاسنان"],
        Experience: "",
        position: "General Dentist",
        department: ["dentist"],
        search: "Dentistry",
        searchid: ["61dc0c29b24354b161efe86c"],
        skills: [
            "Dental Restorations Endodontic Treatments",
            "Pedodontic Treatments",
            "Teeth Bleaching",
            "Prosthodontic",
            "Cleaning and Polishing of teeth",
            "Teeth Extractions",
        ],
        skillsar: [
            "حشوات تجميلية للأسنان",
            "علاج جذور الأسنان",
            "علاج أسنان الأطفال",
            "تبييض الأسنان",
            "تركيبات الأسنان",
            "تنظيف الأسنان وعلاج اللثة",
            "خلع الأسنان",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alnujaym",
    },
    {
        imgUrl: "/assets/real/rehab_ammar.png",
        name: "Dr. Rehab Ammar",
        namear: "	د. رحاب عمار",
        positionar: "	اخصائية جلدية",
        Nationality: "المصرية",
        Qualification: [
            "درجة البكالوريوس في الجراحة العامة (الجلدية والتجميل).",
        ],
        Experience: "9 سنوات",
        position: "Dermatology resident",
        department: ["dermatology"],
        search: "Dermatology and Cosmetology",
        searchid: ["61dc0c29b24354b161efe871"],
        skills: [
            "Dermatopathology ",
            "Peeling( Chemical Type)",
            "Cosmetology",
            "PRP Plastic for hair removal",
            "Acne treatment",
            "Skin diseases",
            "Hyperpigmentation",
        ],
        skillsar: [
            "	الأمراض الجلدية",
            "	التقشير (النوع الكيميائي)",
            "(التجميل)",
            "PRP بلاستيك لإزالة الشعر",
            "علاج حب الشباب",
            "أمراض الجلد",
            " فرط تصبغ",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Rehab_Ammar",
    },
    {
        imgUrl: "/assets/real/mamdouh_oun_alsoud.png",
        name: "Dr. Mamdouh Oun Alsoud",
        namear: "	د. ممدوح عيون السود",
        positionar: "	استشاري جراحة عامة ومناظير",
        Nationality: "السوري",
        Qualification: ["البورد في الجراحات العامة"],
        Experience: "9 سنوات",
        position: " Head of General Surgery and OR",
        department: ["or", "general_surgeon"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        License: ["البورد الأردني والبورد السعودي"],
        skills: [
            "Appendectomy ( open and laproscopic)",
            "Inguinal, Umbilical and Femoral Hernioplasty ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        skillsar: [
            "استئصال الزائدة الدودية( فتح - المنظار)",
            "اصلاح فتق اربي - فتق سري - فتق الفخذ",
            "عمليات جراحة الثدي ب انواعها",
            "عمليات المناظير الجراحية",
            "التدخل العلاجي بواسطة الاشعة الصوتية ",
            "الخزعات الاولية ",
            "الخظعات الكاملة للاورام بكافة انواعها ",
            " شسحب العينات بواسطة الابرة الدقيقة وتحليل الخلايا",
            "مناظير الجراحية التشخيصية ",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mamdouh_Oun_Alsoud",
    },
    {
        imgUrl: "/assets/real/atef_bassas.png",
        name: "Dr. Attif Bassas",
        namear: "	د . عاطف بصاص",
        positionar: "استشاري الجراحة العامة والاورام وجراحات السمنه",
        Nationality: "السعودية",
        Qualification: ["دكتوراه الجراحة العامة في الكلية الملكية الأردنية"],
        Experience: "اكثر من 30 سنة",
        position: "Bariatric Surgeon and General Specialist Surgeon",
        department: ["bariatic", "general_surgeon"],
        search: "Bariatic Surgery",
        searchid: [
            "61dc0c29b24354b161efe876",
            "61dc10a8b24354b161f2f8e2",
            "61dc0c29b24354b161efe86d",
        ],
        License: [
            "الرابطة العالمية للسمنة (IFSD) - الجمعية الأمريكية لأمراض الكبد",
            "متابعة الكلية الملكية للجراحين في إيرلندا",
        ],
        skills: [
            "Tumor operations",
            "All types of obesity operations (re-obesity and morbid obesity)",
            "Gastric Bypass",
            "Gastric Banding",
            "Gastrectomy Sleeve ",
            "Laparoscopic sleeve gastrectomy",
            "SADI operation",
            "SASI process",
            "Oncology surgery",
            "General surgeries",
            "Mini gastric bypass",
        ],
        skillsar: [
            "	عمليات الورم",
            "عمليات السمنة بأنواعها (إعادة السمنة والسمنة المفرطة)",
            "	تحويل مسار المعدة",
            "	ربط المعدة",
            "	تكميم المعدة",
            "	تكميم المعدة بالمنظار",
            "	عملية SADI",
            "	عملية الساسي",
            "	جراحة الأورام",
            "	الجراحات العامة",
            "	المجازة المعدية المصغرة",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Attif_Bassas",
    },
    {
        imgUrl: "/assets/real/asma_saleem.png",
        name: "Dr. Asma Salem",
        namear: "د. اسماء سالم باحارثة",
        positionar: "	استشارية نساء وولادة",
        Nationality: "اليمنية",
        Qualification: ["بكالوريوس طب ، بكالوريوس جراحة"],
        Experience: "16 سنوات واكثر",
        position: "Consultant Gynecology and Obstetrics",
        department: ["obgyna"],
        search: "ob/Gyne",
        searchid: ["61dc0c29b24354b161efe86b"],
        License: [
            "Jordanian Board on obstetric and Gynecology",
            "Arab Board on obstetrics and Gynecology",
            "Diploma and fellowship in FMAS World laparoscopy hospital india",
        ],
        skills: [
            "Caesarian section, extended Episiotomies ",
            "Complicated Genital tract tears",
            "Repair of Cervical tears",
            "Hysterectomies and Vaginal repair",
            "Cyst and laparoscopic Surgeries",
            "Management Postpartum Hemorrhage",
            "Surgical Disturbed ectopic pregnancy",
            "Distortion of ovarian cyst both through laparoscopic and abdominally",
            "Infertility",
        ],
        skillsar: [
            "العملية القيصرية.",
            "تمزق الجهاز التناسلي المعقد",
            "إصلاح تمزقات عنق الرحم",
            "استئصال الرحم وإصلاح المهبل",
            "جراحات الكيس والجراحة بالمنظار",
            "إدارة النزف التالي للوضع",
            "اضطراب الحمل خارج الرحم",
            "تشوه كيس المبيض سواء عن طريق المنظار أو البطن",
            "العقم",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Asma_Salem",
    },
    {
        imgUrl: "/assets/dr/femaledoc.png",
        name: "Dr. Somaya Abbas",
        namear: "	د. سمية عباس",
        positionar: "	استشارية نساء وولادة",
        Nationality: "السودانية",
        Qualification: ["دكتوراة اكلينيكية فى امراض النساء و التوليد"],
        Experience: " 16 سنوات ",
        position: "Consultant Gynecology and Obstetrics",
        department: ["obgyna"],
        search: "ob/Gyne",
        searchid: ["61dc0c29b24354b161efe86b"],
        skills: [
            "Pregnancy diagnoses and pregnancy Care",
            "Birth delivery and Surgical delivery",
            "Ultrasound",
        ],
        skillsar: [
            "تشخيص الحمل ورعاية الحمل",
            "الولادة والولادة الجراحية",
            "الموجات فوق الصوتية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Somaya_Abbas",
    },

    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Hansa Diyab",
        namear: "	د. حسناء دياب",
        positionar: "	اخصائية عيون",
        Nationality: "المصرية",
        Qualification: ["ماجستير طب وجراحة العيون والجراحة"],
        Experience: "15 سنة واكثر",
        position: "Ophthalmology Specialist",
        department: ["ophthalmology"],
        search: "Ophthalmology",
        searchid: ["61dc0c29b24354b161efe86c"],
        skills: [
            "Ophthalmoscope",
            "Retino-scope",
            "Refraction",
            "Surgical Treatment of ophthalmology",
            "Conjunctiva Cyst Removal",
            "Corneal Statues",
            "Wound Stutters",
            "Anterior Segment examination and treatment",
            "Squint Follow up diagnoses and surgery",
        ],
        skillsar: [
            "	منظار العين",
            "	منظار ريتينو",
            "	الانكسار العيون",
            "	العلاج الجراحي لطب العيون",
            "	إزالة كيس الملتحمة",
            "	تماثيل القرنية",
            "	الجروح التعتعة",
            "	فحص وعلاج الجزء الأمامي للعين",
            "	متابعة تشخيص وجراحة الحول",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Hansa_Diyab",
    },
    {
        imgUrl: "/assets/real/malek_hasan.png",
        name: "Dr. Malek Hassan",
        namear: "	د. مالك حسن",
        positionar: "	طبيب عام",
        Nationality: "السورية",
        Qualification: ["درجة البكالوريوس في الطب الجراحة العامة"],
        Experience: "27 سنة واكثر",
        position: "General Practitioner (Head of ER department)",
        department: ["er", "genprac"],
        search: "General Surgery",
        searchid: ["61efcbc89e4660080341bd9d"],
        skills: [
            "Critical cases ",
            "Sutures",
            "Fever",
            "Common Illness",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
            "Hyperlipidemia",
        ],
        skillsar: [
            "	الحالات الحرجة",
            "	الغرز",
            "	الحمى",
            "	المرض المشترك",
            "	الصدمة",
            "	ارتفاع ضغط الدم",
            "	مرض السكري",
            "	فرط شحميات الدم",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Malek_Hassan",
    },
    {
        imgUrl: "/assets/real/abdulfatah_ali.png",
        name: "Dr. Abdulfatah Ali",
        namear: "	د. عبد اللطيف علي",
        positionar: "استشاري الأنف والأذن والحنجرة",
        Nationality: "المصرية",
        Qualification: [" زمالة الكلية الملكية للجراحة"],
        Experience: "30 سنة واكثر",
        position: "ENT Consultant",
        License: ["عضوية جمعية الأنف والحنجرة الأمريكية"],
        department: ["ENT"],
        search: "ENT(Ear, Nose & Throat)",
        searchid: ["61dc0c29b24354b161efe878"],
        skills: [
            "Sinus view surgeries",
            "Diagnose ENT children's problems",
            "Diagnosis of hearing impaired children",
            "Special operations for snoring and sleep diseases",
            "Endoscopy of the upper respiratory tract and esophagus",
            "Laser and radiofrequency surgeries",
            "Microscopic ear operations",
            "Laryngoscopy ",
            "Flexible Nasoendoscopy",
            "Audiometer",
        ],
        skillsar: [
            "جراحات عرض الجيوب الأنفية",
            "تشخيص مشاكل الأطفال في الأنف والأذن والحنجرة",
            "تشخيص الأطفال ضعاف السمع",
            "عمليات خاصة لأمراض الشخير والنوم",
            "مناظير الجهاز التنفسي العلوي والمريء",
            "جراحات الليزر والترددات الراديوية",
            "عمليات الأذن المجهرية",
            "تنظير الحنجرة",
            "تنظير الأنف المرن",
            "مقياس السمع",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abdulfatah_Ali",
    },
    
    {
        imgUrl: "/assets/real/saleh_eid.png",
        name: "Dr. Saleh Eid",
        namear: "	د. صالح عيد",
        positionar: "	اخصائي جراحة عامة",
        Nationality: "المصرية",
        Qualification: ["دبلوم في الجراحة العامة"],
        Experience: "36 سنة واكثر",
        position: "General Surgeon Specialist",
        department: ["general_surgeon"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        skills: [
            "hernia, appendix",
            "Hemorrhoids",
            "anal fissure",
            "circumcision",
        ],
        skillsar: ["فتق ، الملحق", "البواسير", "الشق الشرجي", "الختان"],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Saleh_Eid",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Mohammed Alnather",
        namear: "	د. محمد الناظر",
        positionar: "	اخصائي قلب",
        Nationality: "المصرية",
        Qualification: ["ماجستير في أمراض القلب"],
        Experience: "44 سنة واكثر ",
        position: " Cardiologist and Internal Medicine Consultant",
        department: ["cardiologist", "internalmeds"],
        search: "Cardiologist",
        License: ["الطب الباطني التابع لبريطانيا"],
        searchid: ["61dc0c29b24354b161efe86e", "61de40bca391f298f2fa8a32"],
        skills: [
            "Internal medicine Cases",
            "Cardio Vascular System",
            "Trauma",
            "High Blood Pressure",
            "Diabetes",
        ],
        skillsar: [
            "حالات الطب الباطني",
            "نظام القلب والأوعية الدموية",
            "الصدمة",
            " ارتفاع ضغط الدم",
            "مرض السكري",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alnather",
    },
    {
        imgUrl: "/assets/real/abdulrahman_alsouify.png",
        name: "Dr. Abdulrahman Alsouify",
        namear: "	د. عبدالرحمن السويفي",
        positionar: "أخصائي أمراض الذكورة والمسالك البولية",
        Nationality: "المصرية",
        Qualification: [
            "ماجستير في جراحة المسالك البولية و التناسلية ( جامعة عين شمس)",
        ],
        Experience: "14 سنة ",
        position: "Registrar Urology - Medical Director",
        department: ["urology"],
        search: "Urology",
        searchid: ["61dc0c29b24354b161efe873"],
        skills: [
            "Prostate diseases and infections",
            "Infertility and delayed childbearing",
            "Testicular study",
            "Congenital defects of the cell and penis",
            "Urogenital infections",
            "Kidney, ureter, bladder stones",
        ],
        skillsar: [
            "أمراض والتهابات البروستاتا",
            "العقم وتأخر الإنجاب",
            "دراسة الخصية",
            "العيوب الخلقية في الخلية والقضيب",
            "التهابات الجهاز البولي التناسلي",
            "حصوات الكلى والحالب والمثانة",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Abdulrahman_Alsouify",
    },
    {
        imgUrl: "/assets/real/dania_bawadkji.png",
        name: "Dr. Dania Bawadkji",
        namear: "	د. دنيا باوادكجي",
        positionar: "	طبيبة اسنان",
        Nationality: "السورية",
        Qualification: ["درجة البكالوريوس في طب الأسنان"],
        Experience: "3 سنوات",
        position: "General Dentist",
        department: ["dentist"],
        search: "Dentistry",
        searchid: ["61dc0c29b24354b161efe86f"],
        skills: [
            "Periapical x-ray, panoramic , CT scan.",
            "Removable prosthodontics.",
            "Fixed prosthodontics",
            "Gum treatment",
            "Orthodontics",
            "Cosmetic fillings",
            "Root Canal",
            "Filling",
            "Denture",
            "General and surgical Extraction",
        ],
        skillsar: [
            "الأشعة السينية ، بانورامية ، الأشعة المقطعية.",
            "التركيبات القابلة للإزالة.",
            "التركيبات الثابتة.",
            "علاج اللثة",
            "تقويم الأسنان",
            "حشوات تجميلية",
            "قناة الجذر",
            "الحشوة",
            "طقم أسنان",
            "الخلع العام والجراحي",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Dania_Bawadkji",
    },
    {
        imgUrl: "/assets/dr/maledoc.png",
        name: "Dr. Alaa Mohammed",
        namear: "	د. علاء محمد",
        positionar: "	اخصائي عظام",
        Nationality: "المصرية",
        Qualification: ["درجة الماجستير في جراحة العظام"],
        Experience: "3 سنوات",
        position: "Orthopedics Specialist",
        department: ["orthopedics"],
        search: "Orthopedics",
        searchid: ["61dc0c29b24354b161efe872"],
        skills: [
            "Joint Diseases",
            "Tumors",
            "Trauma closed and open reduction ",
            "Local joint Injections",
            "Plaster cast (POP)",
            "Tendon repair ",
            "Arthroplasty",
            "Sports Injury",
        ],
        skillsar: [
            "أمراض المفاصل",
            "الأورام",
            "الصدمة مغلقة وفتح الحد",
            "حقن المفاصل المحلية",
            "(POP) الجبس ",
            "إصلاح الأوتار",
            "تقويم المفاصل",
            "الإصابات الرياضية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Alaa_Mohammed",
    },
    {
        imgUrl: "/assets/real/eman_mohammad.png",
        name: "Dr. Eman Mohammed",
        namear: "	د. ايمان محمود",
        positionar: "	اخصائية اطفال",
        Nationality: "الصينية",
        Qualification: ["مسجل البورد السعودي لطب الأطفال"],
        Experience: "6 سنوات",
        position: "Pediatric Specialist",
        department: ["pediatrics"],
        search: "pediatric",
        searchid: ["61dc0c29b24354b161efe86a"],
        skills: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
        ],
        skillsar: [
            "أمراض الجهاز الهضمي",
            "مرض الرئة (الربو)",
            "ومضات الاكتئاب",
            "الأطفال حديثي الولادة",
            "الأنفلونزا المعوية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Eman_Mohammed",
    },
    {
        imgUrl: "/assets/real/3.png",
        name: "Dr. Mohammed Alsamamni",
        namear: "	د. محمد السماني",
        positionar: "	اخصائي علاج طبيعي",
        Nationality: "السودانية",
        Qualification: ["درجة البكالوريوس في العلاج الطبيعي"],
        Experience: "30 سنة واكثر",
        position: "Physiotherapist Specialist ",
        department: ["physiotherapist"],
        License: ["دراسات جمهورية التشيك"],
        search: "Physiotherapy",
        searchid: ["61dc0c29b24354b161efe877"],
        skills: [
            "Treating orthopedic and neurological diseases",
            "Sports injury rehabilitation",
            "thromboembolism treatment",
            "Rehabilitation of handicapped children",
            "Facial nerve treatment",
        ],
        skillsar: [
            "علاج أمراض العظام والجهاز العصبي",
            "تأهيل الإصابات الرياضية",
            "علاج الجلطات الدموية",
            "تأهيل الأطفال المعوقين",
            "علاج عصب الوجه",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Mohammed_Alsamamni",
    },
    {
        imgUrl: "/assets/real/ahmad_ali.png",
        name: "Dr. Ahmed Ali",
        namear: "	د. أحمد علي",
        positionar: "	استشاري باطنية وجهاز هضمي",
        Nationality: "المصرية",
        Qualification: ["دكتوراه الطب الباطني"],
        Experience: "30 سنة واكثر",
        position:
            "Consultant and Professor of internal Medicine / Head of Internal Medicine Dept.",
        department: ["internalmeds"],
        search: "internalmeds",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        skills: [
            "Chest allergy",
            "High blood pressure",
            "Chronic diabetes",
            "Gastrointestinal diseases",
            "Incision biopsy",
            "Excision Biopsy",
            "FNAC",
            "Diagnostic Laparoscopy",
            "Respiratory system",
            "Digestive system",
        ],
        skillsar: [
            "حساسية الصدر",
            "ارتفاع ضغط الدم",
            "مرض السكري المزمن",
            "أمراض الجهاز الهضمي",
            "تنظير البطن التشخيصي",
            "الجهاز التنفسي",
            "الجهاز الهضمي",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ahmed_Ali",
    },
    {
        imgUrl: "/assets/real/ibrahim_rusidi.png",
        name: "Dr. Ibrahim Rushdi",
        namear: "	د. إبراهيم رشدي",
        positionar: "	اخصائي اطفال",
        Nationality: "المصرية",
        Qualification: ["درجة الماجستير في طب الأطفال"],
        Experience: "30 سنة واكثر",
        position: "Head of the Department of Pediatrics and Neonatology",
        department: ["pediatrics"],
        search: "pediatric",
        searchid: ["61dc0c29b24354b161efe86a"],
        skills: [
            "Gastrointestinal diseases",
            "Lung disease (asthma)",
            "dysthymic flashes",
            "newborn babies",
            "Intestinal flu",
        ],
        skillsar: [
            "أمراض الجهاز الهضمي",
            " مرض الرئة (الربو)",
            "ومضات الاكتئاب",
            "الأطفال حديثي الولادة",
            "الأنفلونزا المعوية",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ibrahim_Rushdi",
    },
    {
        imgUrl: "/assets/real/almad_nader.png",
        name: "Dr. Ahmed Nader",
        namear: "	د. أحمد نادر",
        positionar: "	اخصائي اول جراحة عامة",
        Nationality: "فلسطيني",
        Qualification: ["البورد الأردني في الجراحة العامة"],
        Experience: "7 سنوات",
        position: "Senior registrar General Surgery",
        department: ["general_surgeon"],
        search: "General Surgery",
        searchid: ["61dc10a8b24354b161f2f8e2"],
        License: ["عضوية المجلس الطبي الأردني", "عضوية اطباء جامعة مؤتة "],
        skills: [
            "Appendectomy ( open and laproscopic)",
            "Mastectomy",
            "Laparoscopic surgery ",
            "US Guided Intervention",
            "FNAC",
            "Diagnostic Laparoscopy",
        ],
        skillsar: [
            "استئصال الزائدة الدودية (بالمنظار والفتح)",
            "استئصال الثدي",
            "جراحة المناظير",
            " التدخل الأمريكي الموجه",
            "FNAC",
            "تنظير البطن التشخيصي",
        ],
        mobno: "+00 0000 0000 00",
        email: "roberto@medwise.com",
        linkto: "Ahmed_Nader",
    },
    
];

export default { demoDatas };
